"""Emit the plain-text title and abstract the submission form asks to be pasted in.

    python paper/make_susy_fields.py    # -> paper/susy_medphys_fields.txt

The form holds its own copy of the title and abstract, typed into a web page. That copy
was maintained by hand and is the third place in this submission where a copy of the
front matter drifted from the paper it describes: the abstract still said the two networks
differed "at two capacities" after Contribution 5 and Section 3.6 had both been corrected
to say they differ in three respects at once. A copy that is generated cannot drift.

Markdown emphasis, code spans and the results markers are resolved or stripped, because
the form takes plain text and renders none of them.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PAPER = Path(__file__).resolve().parent
BUILT = PAPER / "build" / "manuscript.md"
OUT = PAPER / "susy_medphys_fields.txt"

#: Limits the form enforces.
TITLE_CHARACTERS = 145
ABSTRACT_WORDS = 500


def plain(text: str) -> str:
    """Markdown down to what a plain-text field can carry."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text, flags=re.S)
    text = re.sub(r"\*(.+?)\*", r"\1", text, flags=re.S)
    text = re.sub(r"`(.+?)`", r"\1", text, flags=re.S)
    return re.sub(r"[ \t]+", " ", text).strip()


def main() -> int:
    if not BUILT.exists():
        print("build/manuscript.md missing - run paper/build_manuscript.py first")
        return 2
    body = re.sub(r"<!--.*?-->", "", BUILT.read_text(encoding="utf-8"), flags=re.S)

    title = plain(next(ln[2:] for ln in body.splitlines() if ln.startswith("# ")))
    abstract = plain(body.split("## Abstract")[1].split("**Keywords")[0])
    keywords = plain(body.split("**Keywords:**")[1].split("\n\n")[0])

    # The form takes the abstract as one block; the run-in labels stay, the line breaks go.
    abstract = "\n\n".join(
        " ".join(paragraph.split()) for paragraph in abstract.split("\n\n") if paragraph.strip()
    )
    words = len(abstract.split())

    OUT.write_text(
        f"=== TITLE ({len(title)} / {TITLE_CHARACTERS} characters) ===\n{title}\n\n"
        f"=== ABSTRACT ({words} / {ABSTRACT_WORDS} words) ===\n{abstract}\n\n"
        f"=== KEYWORDS ===\n{keywords}\n\n"
        "Generated by paper/make_susy_fields.py from build/manuscript.md. Do not edit by\n"
        "hand: the form's copy of the front matter has drifted from the paper before.\n",
        encoding="utf-8",
    )

    over = []
    if len(title) > TITLE_CHARACTERS:
        over.append(f"title is {len(title)} characters, over {TITLE_CHARACTERS}")
    if words > ABSTRACT_WORDS:
        over.append(f"abstract is {words} words, over {ABSTRACT_WORDS}")
    print(f"wrote {OUT}")
    print(f"  title {len(title)}/{TITLE_CHARACTERS} chars, abstract {words}/{ABSTRACT_WORDS} words")
    for message in over:
        print(f"  OVER LIMIT: {message}")
    return 1 if over else 0


if __name__ == "__main__":
    sys.exit(main())
